config/routes.rb
Moneymaker::Application.routes.draw do
  get "home/index"
  get "nintendo" => "home", :as => :nintendo
  get "yahoo" => "home", :as => :yahoo
  get "microsoft" => "home", :as => :microsoft
  get "zynga" => "home", :as => :zynga
  get "intel" => "home", :as => :intel

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # default to show Google Data
    @company = 'Google (GOOG)'
    @actual = false
    @up = true
    @file = 'google_counts.csv'
  end

  def nintendo
    @company = 'Nintendo (NTDOY)'
    @file = 'nintendo_counts.csv'
    @actual = true
    @up = false
    render :index
  end

  def zynga
    @company = 'Zynga (ZNGA)'
    @file = 'zynga_counts.csv'
    @actual = false
    @up = false
    render :index
  end

  def microsoft
    @company = 'Microsoft (MSFT)'
    @file = 'microsoft_counts.csv'
    @actual = true
    @up = false
    render :index
  end

  def yahoo
    @company = 'Yahoo (YHOO)'
    @file = 'yahoo_counts.csv'
    @actual = true
    @up = true
    render :index
  end

  def intel
    @company = 'Intel (INTC)'
    @file = 'intel_counts.csv'
    @actual = false
    @up = true
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_graph.html.haml
:javascript
  $(function () {
      var chart,
          chart2, // globally available
          percentage = function(arr1, arr2) {
                        var total;
                        if (arr1.length != arr2.length) {
                          return false;
                        } else {
                          for (var i=0; i<arr1.length; i++) {
                            total = arr1[i] + arr2[i];
                            arr1[i] = arr1[i] / total;
                            arr2[i] = arr2[i] / total;
                          }
                          return true;
                        }
                      };
      $(document).ready(function() {
          options = {
                      chart: {
                          renderTo: 'fig1',
                          type: 'bar'
                      },
                      title: {
                          text: 'Weekly TweetSentiment'
                      },
                      subtitle: {
                          text: 'Source: Twitter Public API'
                      },
                      xAxis: [{
                          categories: [],
                          reversed: false
                      }, { // mirror axis on right side
                          opposite: true,
                          reversed: false,
                          categories: [],
                          linkedTo: 0
                      }],
                      yAxis: {
                          title: {
                              text: null
                          },
                          labels: {
                              formatter: function(){
                                  return Math.abs(this.value);
                              }
                          },
                          min: 0,
                          max: 0
                      },
                      plotOptions: {
                          series: {
                              stacking: 'normal'
                          }
                      },
                      tooltip: {
                          valueDecimals: 2,
                          formatter: function(){
                              return '<b>' + this.point.category +'</b><br/>'+
                                  this.series.name + ': '+ Highcharts.numberFormat(Math.abs(this.point.y)*100, 2) + '%';
                          }
                      },
                      series: [{
                          name: 'Positive',
                          data: []
                          }, {
                          name: 'Negative',
                          data: []
                      }]
                    };
          options2 = {
                        chart: {
                            renderTo: 'fig2',
                            type: 'spline'
                        },
                        title: {
                            text: 'Total Volume of Tweets'
                        },
                        subtitle: {
                            text: 'Source: Twitter Public API'
                        },
                        xAxis: {
                            categories: []
                        },
                        yAxis: {
                            title: {
                                text: 'Num of Tweets'
                            },
                            labels: {
                                formatter: function() {
                                    return this.value
                                }
                            }
                        },
                        tooltip: {
                            crosshairs: {
                                width: 2,
                                color: 'gray',
                                dashStyle: 'shortdot'
                            },
                            formatter: function(){
                                            return '<b>' + this.point.category +'</b><br/>'+
                                                  'Total Tweets: '+ Highcharts.numberFormat(Math.abs(this.point.y), 0);
                                        }
                        },
                        plotOptions: {
                            spline: {
                                marker: {
                                    radius: 4,
                                    lineColor: '#666666',
                                    lineWidth: 1
                                }
                            }
                        },
                        series: [{
                            name: '#{company}',
                            marker: {
                                symbol: 'square'
                            },
                            data: []
                        }]
                    };

          $.get("#{file}", function(data) {
              // Split the lines
              var lines = data.split('\n'),
                  len = lines.length,
                  dates = [],
                  pos = [],
                  negs = [],
                  max = 0,
                  dates = [],
                  total = [];
              // Iterate over the lines and add categories or series
              $.each(lines, function(lineNo, line) {
                var items = line.split(',');

                if (lineNo != 0 && lineNo != len - 1) {
                  $.each(items, function(itemNo, item) {
                    if (itemNo == 0) {
                      dates.unshift(item);
                    } else if (itemNo == 1) {
                      pos.unshift(parseInt(item, 10));
                    } else if (itemNo == 2) {
                      negs.unshift(parseInt(item, 10));
                    }
                  });
                }
              });
              percentage(pos, negs);

              max = 1; //Math.max(Math.max.apply(Math, pos), Math.max.apply(Math, negs)) + 5;
              options.xAxis[0].categories = dates;
              options.xAxis[1].categories = dates;
              options.series[0].data = pos.map(function(val) {return -1*val;});
              options.series[1].data = negs;
              options.yAxis.min = -1 * max;
              options.yAxis.max = max;
              // Create the chart
              chart = new Highcharts.Chart(options);

              dates = []

              // Iterate over the lines and add categories or series
              $.each(lines, function(lineNo, line) {
                var items = line.split(',');
                if (lineNo != 0 && lineNo != len - 1) {
                  var elem;
                  $.each(items, function(itemNo, item) {
                    if (itemNo == 0) {
                      dates.push(item);
                    } else if (itemNo == 4) {
                      elem = {
                              y: parseInt(item, 10),
                              marker: {
                                symbol: 'url(stock_index_up.png)'
                              }
                             };
                      if (items[5] == 0) {
                        elem.marker.symbol = 'url(stock_index_down.png)'
                      }
                      total.push(elem);
                    }
                  });
                }
              });
              //max = Math.max(Math.max.apply(Math, total), Math.max.apply(Math, total)) + 5;
              options2.xAxis.categories = dates;
              options2.series[0].data = total;
              // Create the chart
              chart2 = new Highcharts.Chart(options2);
            }, "text");
      });
  });

app/views/home/index.html.haml
.row#comp_name
  .span8.offset2.top #{@company}
.row#prediction
  .span8.offset2.top
    Today's Prediction:
    - if @up
      %span.flag#up ▴
    - else
      %span.flag#down ▾

.row#actual
  .span8.offset2.top
    Actual:
    - if @actual
      %span.flag#up ▴
    - else
      %span.flag#down ▾

.clear

= render :partial => "graph", :locals => { :file => @file , :company => @company }

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "Moneymaker"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"
    = javascript_include_tag "http://code.highcharts.com/highcharts.js"
    -#= javascript_include_tag "http://code.highcharts.com/modules/exporting.js"

    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "MoneyMaker", root_path, :class => "brand"
          .container.nav-collapse
            %ul.nav
              %li= link_to "Google", root_path
              %li= link_to "Zynga", zynga_path
              %li= link_to "Microsoft", microsoft_path
              %li= link_to "Intel", intel_path
              %li= link_to "Yahoo", yahoo_path
              %li= link_to "Nintendo", nintendo_path

    .container
      .content
        = yield
        .row#plots
          .span6.fig#fig1
          .span6.fig#fig2

      %footer#footer
        %p#copyright &copy; Data Science Group #{Time.now.year}
        %p#authors
          = link_to "Muller Zhang", "http://coursekit.com/profile/18629"
          |
          = link_to "Linda Dai", "http://coursekit.com/profile/18212"
          |
          = link_to "Jian P. Chen", "http://coursekit.com/profile/17400"

    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"